---

# Minio binaries path
minio_server_bin: /usr/local/bin/minio
minio_client_bin: /usr/local/bin/mc

# Minio release to install. default if lastet
minio_server_release: ""
minio_client_release: ""

# Runtime user and group for the Minio server service
minio_user: minio
minio_group: minio

# Path to the file containing the ENV variables for the Minio server
minio_server_envfile: /etc/default/minio

# Minio server listen address
minio_server_addr: ":9091"

# Minio server data directories
minio_server_datadirs:
  - "/mnt/disks/minio1"
  - "/mnt/disks/minio2"
  - "/mnt/disks/minio3"
  - "/mnt/disks/minio4"
  - "/mnt/disks/minio5"
  - "/mnt/disks/minio6"
  - "/mnt/disks/minio7"
  - "/mnt/disks/minio8"
  
minio_server_make_datadirs: true

# Minio access and secret keys
minio_access_key: "mehmet"
minio_secret_key: "mehmet"

# Switches to enable/disable the Minio server and/or Minio client installation.
minio_install_server: true
minio_install_client: true